### ISSUE TITLE
"duplicate validator function" error while importing Feature class form geojson_pydantic

### ISSUE THREAD

**Issue by vishalratnam6** [developmentseed/geojson-pydantic#120] opened 2023-05-11 07:39 UTC
I've created a dataclass `Abc` :

```
from geojson_pydantic import Feature
from dataclasses import dataclass

@dataclass
class Abc:
    geojson: Feature
    myid: uuid.UUID
```

This model is present in `commons.py` file inside `dtos` folder.

I'm trying to import Abc from `main.py` and one other file.

Directory Structure:
```
src -->
    --> dtos
           - commons.py -> Abc
    --> anothermodule
           - create.py -> from dtos.commons import Abc
    main.py -> import dtos.commons.Abc
```

I get this error when I run the `main.py` file

```
File "<frozen importlib._bootstrap>", line 1109, in __import__
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/anaconda3/envs/apsbackend/lib/python3.9/site-packages/geojson_pydantic/geometries.py", line 175, in <module>
    class Polygon(_GeometryBase):
  File "/usr/local/anaconda3/envs/apsbackend/lib/python3.9/site-packages/geojson_pydantic/geometries.py", line 186, in Polygon
    def check_closure(cls, coordinates: List) -> List:
  File "pydantic/class_validators.py", line 93, in pydantic.class_validators.validator.dec
  File "pydantic/class_validators.py", line 156, in pydantic.class_validators._prepare_validator
pydantic.errors.ConfigError: duplicate validator function "geojson_pydantic.geometries.Polygon.check_closure"; if this is intended, set `allow_reuse=True`
```

**Comment by vincentsarago** [comment] 2023-05-11 11:18
@vishalratnam6 can you tell what version of geojson-pydantic you are using please 🙏

**Comment by vishalratnam6** [comment] 2023-05-11 11:31
@vincentsarago I'm using the latest version of geojson-pydantic, version `0.6.0`

**Comment by vincentsarago** [comment] 2023-05-11 16:49
@vishalratnam6 

I've tried something locally but I haven't been able to reproduce your issue 🤷‍♂️ 

I've started https://github.com/developmentseed/geojson-pydantic/pull/121 but this is pure guess. could you try this branch and see if it fix your issue?

**Comment by vincentsarago** [comment] 2023-05-11 19:05
ok I closed #121 because it's definitely not what I though. 

This is really weird. Did you get the same error when using version `0.5` ?

**Comment by vishalratnam6** [comment] 2023-05-11 19:08
Yes, the same error, but it pointed at a different file with version 0.5.
It pointed at the LinearRingGeom class with the same allow_reuse error.

**Comment by vincentsarago** [comment] 2023-05-11 19:09
Cool 🙏 

I'm really sorry, but without a proper reproducible example it's really hard for me to help more 😭

**Comment by vishalratnam6** [comment] 2023-05-11 19:13
Here's my email: vishalratnam@gmail.com, please let me know if we can discuss this over a call!

**Comment by vincentsarago** [comment] 2023-05-11 19:15
@vishalratnam6 I think it would be simpler if you create a small repo in GitHub with a simple reproductible example 🙏

**Comment by vishalratnam6** [comment] 2023-05-11 19:33
Hey @vincentsarago, I've created [this repo](https://github.com/vishalratnam6/pydatic_test). 
You'll need to install [temporal](https://docs.temporal.io/application-development/foundations) and start the server locally.
Then you've to run `pip install temporalio` and obv `pip install geojson_pydantic`.
Post this, if you run `python3 main.py`, it'll throw the same error!

**Comment by vincentsarago** [comment] 2023-05-11 20:53
I don't think this is a geojson-pydantic issue! There's definitely something going on with Temporal. I provided a `fix` directly in the example repo so I'm going to close this issue for now 🙏

**Closed by vincentsarago** 2023-05-11 20:53 UTC
